quarkus:
  cache:
    caffeine:
      "remote-writer-settings":
        expire-after-write: 120S
  http:
    port: ${SERVER_PORT:8883}
    cors:
      ~: true
    ssl:
      certificate:
        key-store-file-type: JKS
        key-store-password: ${KEYSTORE_PASSWORD}
        key-store-alias: ${KEYSTORE_CERT_ALIAS}
        key-store-file: /security/keystore.jks
    ssl-port: ${SERVER_SSL_PORT:8443}
    insecure-requests: redirect
  datasource:
    db-kind: postgresql
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}
    jdbc:
      url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:25432}/${DATABASE_NAME:postgres}
      min-size: 1
      max-size: 10
  hibernate-orm:
    log:
      sql: false
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database:
      generation: none
  smallrye-graphql:
    print-data-fetcher-exception: true
    error-extension-fields:
      - exception
      - description
  log:
    level: DEBUG
    min-level: TRACE
    console:
      level: INFO
      format: "%d{YYYY-MM-DD'T'HH:mm:ss} %-5p %X{X-Correlation-Id} [%c{2.}] (%t) %s%e%n"
    category:
      "cz.blackshark.http.filter":
        level: TRACE
      "org.jboss.resteasy.client":
        level: DEBUG
    file:
      enable: true
      level: DEBUG
      path: log/app.log
      format: "%d{YYYY-MM-dd'T'HH:mm:ss} %-5p %X{X-Correlation-Id} [%c{2.}] (%t) %s%e%n"
      rotation:
        max-file-size: "10M"
        max-backup-index: 4
  liquibase:
    migrate-at-start: true
    default-schema-name: public
    change-log: database/changeLog.xml
    database-change-log-table-name: databasechangelog
  keycloak:
    admin-client:
      server-url: ${QUARKUS_ADMIN_URL}
      username: ${QUARKUS_ADMIN_USERNAME}
      password: ${QUARKUS_ADMIN_PASSWORD}
      client-id: ${QUARKUS_ADMIN_CLIENT_ID}
      client-secret: ${QUARKUS_ADMIN_CLIENT_SECRET}
      realm: ${QUARKUS_ADMIN_REALM}
application:
  jax-rs-date-format: yyyy-MM-dd
  file-storage-path: ${FILE_STORAGE_PATH}
jira:
  username: ${JIRA_USERNAME}
  token: ${JIRA_TOKEN}
  account-id: ${JIRA_ACCOUNT_ID}
gemts:
  username: ${TIMESHEET_USERNAME}
  password: ${TIMESHEET_PASSWORD}
  dr-max-project-name: "DrMax integrační platforma"
ares-api/mp-rest/url: "http://wwwinfo.mfcr.cz"
ares-api/mp-rest/scope: "javax.inject.Singleton"

drmax-jira/mp-rest/url: ${DRMAX_TIMESHEET_URL}
drmax-jira/mp-rest/scope: "javax.inject.Singleton"

gem-timesheet/mp-rest/url: ${GEM_TIMESHEET_URL}
gem-timesheet/mp-rest/scope: "javax.inject.Singleton"




"%test":
  quarkus:
    log:
      level: INFO
      min-level: DEBUG
      file:
        format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %X{X_CORRELATION_ID} [%c{3.}] (%t) %s%e%n"
        path: "log/aps_poc_log.log"
        rotation:
          max-backup-index: 10
          max-file-size: "20M"
        enable: true
