quarkus:
  cache:
    caffeine:
      "remote-writer-settings":
        expire-after-write: 120S
      "user-by-subject-id":
        expire-after-write: 600S
      "user-entity":
        expire-after-access: 60S
        maximum-size: 100

  http:
    port: ${SERVER_PORT:8883}
    cors:
      ~: true
      origins:
        - /.*/
    host: ${HOST_NAME:timesheet.local.cz}
    auth:
      proactive: true
      permission:
        free:
          paths:
            - /login
            - /*.js
            - /*.css
            - /user/current
          policy: permit
        authenticated:
          paths:
            - /
            - /test
          policy: authenticated
      form:
        enabled: true
        login-page: /login
        error-page: /login?error=1
        redirect-after-login: true
  datasource:
    db-kind: postgresql
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}
    jdbc:
      url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:25432}/${DATABASE_NAME:postgres}
      min-size: 1
      max-size: 100
  hibernate-orm:
    log:
      sql: false
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database:
      generation: none
  smallrye-graphql:
    print-data-fetcher-exception: true
    error-extension-fields:
      - exception
      - description
  log:
    level: DEBUG
    min-level: DEBUG
    console:
      level: INFO
      min-level: DEBUG
      format: "%d{YYYY-MM-DD'T'HH:mm:ss} %-5p %X{X-Correlation-Id} [%c{2.}] (%t) %s%e%n"
      category:
        "cz.blackshark.modules.main.persistence.repository":
          level: DEBUG
    file:
      enable: true
      level: INFO
      min-level: DEBUG
      path: log/app.log
      format: "%d{YYYY-MM-dd'T'HH:mm:ss} %-5p %X{X-Correlation-Id} [%c{2.}] (%t) %s%e%n"
      rotation:
        max-file-size: "10M"
        max-backup-index: 4
    category:
      "cz.blackshark.modules.main.persistence.repository":
        level: DEBUG
      "cz.blackshark.modules.main.http.controller":
        level: DEBUG
      "cz.blackshark.modules.main.http.filter":
        level: INFO
      "org.jboss.resteasy.client":
        level: INFO

  liquibase:
    migrate-at-start: true
    change-log: database/changeLog.xml
    database-change-log-table-name: databasechangelog
application:
  jax-rs-date-format: yyyy-MM-dd
  file-storage-path: ${FILE_STORAGE_PATH}
jira:
  username: ${JIRA_USERNAME}
  token: ${JIRA_TOKEN}
  account-id: ${JIRA_ACCOUNT_ID}
gemts:
  url: ${GEM_TIMESHEET_URL}
  username: ${TIMESHEET_USERNAME}
  password: ${TIMESHEET_PASSWORD}
  dr-max-project-name: "DrMax integrační platforma"
ares-api/mp-rest/url: "http://wwwinfo.mfcr.cz"
ares-api/mp-rest/scope: "javax.inject.Singleton"

ares-api-2/mp-rest/url: "https://ares.gov.cz"
ares-api-2/mp-rest/scope: "javax.injext.Singleton"

drmax-jira/mp-rest/url: ${DRMAX_TIMESHEET_URL}
drmax-jira/mp-rest/scope: "javax.inject.Singleton"

gem-timesheet/mp-rest/url: ${GEM_TIMESHEET_URL}
gem-timesheet/mp-rest/scope: "javax.inject.Singleton"
