version: '3.6'

services:
  ts-app-psql-database:
    image: postgres:14
    container_name: ts-app-psql-database
    restart: 'no'
    ports:
      - '25432:5432'
    networks:
      - timesheet-3-net
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
networks:
  timesheet-3-net:
