### Try login
POST http://localhost:8887/j_security_check
Content-Type: application/x-www-form-urlencoded
X-Httpclient-Option-Redirects: false


j_username={{login}}&j_password={{password}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 302, "Response status is not 302");
    });
%}



### Try set new password
POST http://localhost:8887/user/password
Content-Type: application/json

{
  "subject": "e3126da8-8c0d-4bc0-b24c-b78565e726c4",
  "oldPassword": "1234567890",
  "newPassword": "12345678"
}
