-- liquibase formatted sql

-- changeset jiri:1611904497273-1
CREATE TABLE "company" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "ic" VARCHAR(256) NOT NULL, "company_name" VARCHAR(256) NOT NULL, "okres" VARCHAR(256) NOT NULL, "obec" VARCHAR(256) NOT NULL, "cast_obce" VARCHAR(256) NOT NULL, "ulice" VARCHAR(256) NOT NULL, "cislo_domu" VARCHAR(256) NOT NULL, "ps" VARCHAR(256) NOT NULL, "dic" VARCHAR(256), "platce_dph" BOOLEAN, "email" VARCHAR(256) NOT NULL, "phone_number" VARCHAR(256) NOT NULL, "primary_account" BOOLEAN DEFAULT FALSE NOT NULL, "bank_account_number" VARCHAR(256) NOT NULL, CONSTRAINT "company_pkey" PRIMARY KEY ("id"));

-- changeset jiri:1611904497273-2
CREATE TABLE "invoice_number" ("company_id" INTEGER NOT NULL, "prefix" INTEGER NOT NULL, "current_val" INTEGER DEFAULT 1 NOT NULL, CONSTRAINT "invoice_number_pkey" PRIMARY KEY ("company_id"));

-- changeset jiri:1611904497273-3
CREATE SEQUENCE  IF NOT EXISTS "company_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset jiri:1611904497273-4
CREATE TABLE "invoice_item" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "price" numeric(9, 2) NOT NULL, "vat" numeric(9, 2), "total_price" numeric(9, 2) NOT NULL, "invoice_id" VARCHAR(16), "requisition_id" INTEGER, "note" TEXT, CONSTRAINT "invoice_item_pkey" PRIMARY KEY ("id"));

-- changeset jiri:1611904497273-5
CREATE SEQUENCE  IF NOT EXISTS "invoice_item_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset jiri:1611904497273-6
CREATE TABLE "project" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(256) NOT NULL, "company_id" INTEGER NOT NULL, CONSTRAINT "project_pkey" PRIMARY KEY ("id"));

-- changeset jiri:1611904497273-7
CREATE SEQUENCE  IF NOT EXISTS "project_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset jiri:1611904497273-8
CREATE TABLE "rate" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "rate" numeric(7, 2) NOT NULL, "valid_since" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "company_id" INTEGER NOT NULL, CONSTRAINT "rate_pkey" PRIMARY KEY ("id"));

-- changeset jiri:1611904497273-9
CREATE SEQUENCE  IF NOT EXISTS "rate_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset jiri:1611904497273-10
CREATE TABLE "requisition" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "company_id" INTEGER, "cust_number" VARCHAR(128) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "note" TEXT NOT NULL, "path" VARCHAR(256) NOT NULL, "orig_name" VARCHAR(256) NOT NULL, CONSTRAINT "requisition_pkey" PRIMARY KEY ("id"));

-- changeset jiri:1611904497273-11
CREATE SEQUENCE  IF NOT EXISTS "requisition_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset jiri:1611904497273-12
CREATE TABLE "static_invoice" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "i_number" VARCHAR(16) NOT NULL, "recipient_id" INTEGER NOT NULL, "issuer_id" INTEGER NOT NULL, "issue_date" date NOT NULL, "payment_date" date NOT NULL, "vat_payment_date" date, "price" numeric(9, 2) NOT NULL, "vat" numeric(9, 2), "total_price" numeric(9, 2) NOT NULL, "note" TEXT NOT NULL, "store_file_name" VARCHAR(128) NOT NULL, CONSTRAINT "static_invoice_pkey" PRIMARY KEY ("id"));

-- changeset jiri:1611904497273-13
CREATE SEQUENCE  IF NOT EXISTS "static_invoice_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset jiri:1611904497273-14
CREATE TABLE "timeline" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "project_id" INTEGER NOT NULL, "from_time" TIMESTAMP WITH TIME ZONE NOT NULL, "to_time" TIMESTAMP WITH TIME ZONE NOT NULL, "pause" INTEGER DEFAULT 0 NOT NULL, "note" TEXT NOT NULL, "invoice_item_id" INTEGER, CONSTRAINT "timeline_pkey" PRIMARY KEY ("id"));

-- changeset jiri:1611904497273-15
CREATE SEQUENCE  IF NOT EXISTS "timeline_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset jiri:1611904497273-16
CREATE TABLE "invoice" ("i_number" VARCHAR(16) NOT NULL, "recipient_id" INTEGER NOT NULL, "issuer_id" INTEGER NOT NULL, "issue_date" TIMESTAMP WITH TIME ZONE NOT NULL, "payment_date" TIMESTAMP WITH TIME ZONE NOT NULL, "vat_payment_date" TIMESTAMP WITH TIME ZONE, CONSTRAINT "invoice_pkey" PRIMARY KEY ("i_number"));

-- changeset jiri:1611904497273-17
ALTER TABLE "invoice" ADD CONSTRAINT "invoice_issuer_id_fkey" FOREIGN KEY ("issuer_id") REFERENCES "company" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-18
ALTER TABLE "invoice_number" ADD CONSTRAINT "invoice_number_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "company" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-19
ALTER TABLE "invoice" ADD CONSTRAINT "invoice_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "company" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-20
ALTER TABLE "project" ADD CONSTRAINT "project_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "company" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset jiri:1611904497273-21
ALTER TABLE "rate" ADD CONSTRAINT "rate_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "company" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-22
ALTER TABLE "requisition" ADD CONSTRAINT "requisition_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "company" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-23
ALTER TABLE "static_invoice" ADD CONSTRAINT "static_invoice_issuer_id_fkey" FOREIGN KEY ("issuer_id") REFERENCES "company" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-24
ALTER TABLE "static_invoice" ADD CONSTRAINT "static_invoice_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "company" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-25
CREATE VIEW "v_timeline_agg" AS SELECT comp.id AS company_id,
                                       comp.company_name,
                                       proj.id AS project_id,
                                       proj.name,
                                       t.id AS timeline_id,
                                       t.from_time,
                                       t.to_time,
                                       ((t.to_time - t.from_time) - make_interval(mins => t.pause)) AS work_time,
                                       t.invoice_item_id
                                FROM ((company comp
                                    JOIN project proj ON ((comp.id = proj.company_id)))
                                         JOIN timeline t ON ((proj.id = t.project_id)))
                                WHERE (((t.to_time - t.from_time) - make_interval(mins => t.pause)) > '00:00:00'::interval);;

-- changeset jiri:1611904497273-26
ALTER TABLE "timeline" ADD CONSTRAINT "timeline_invoice_item_id_fkey" FOREIGN KEY ("invoice_item_id") REFERENCES "invoice_item" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-27
ALTER TABLE "timeline" ADD CONSTRAINT "timeline_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-28
ALTER TABLE "requisition" ADD CONSTRAINT "requisition_company_id_cust_number_key" UNIQUE ("company_id", "cust_number");

-- changeset jiri:1611904497273-29
ALTER TABLE "invoice_item" ADD CONSTRAINT "invoice_item_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "invoice" ("i_number") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset jiri:1611904497273-30
ALTER TABLE "invoice_item" ADD CONSTRAINT "invoice_item_requisition_id_fkey" FOREIGN KEY ("requisition_id") REFERENCES "requisition" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

